### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by brunolemos** [react-component/trigger#288] opened 2022-03-31 04:34 UTC
It's not working when using the new `createRoot` from React 18. Works when using the legacy `ReactDOM.render`.

Depending on the align value it may even freeze the application.

https://codesandbox.io/s/sweet-solomon-j2nuv6

**Comment by gaearon** [comment] 2022-04-03 16:59
We're also seeing async infinite loop in `antd` with React 18 which happen inside `rc-trigger` and `rc-align`.

<img width="759" alt="Screenshot 2022-04-03 at 17 47 50" src="https://user-images.githubusercontent.com/810438/161439193-51c52911-9775-4904-93cd-adb98abd6eac.png">

<img width="452" alt="Screenshot 2022-04-03 at 17 59 46" src="https://user-images.githubusercontent.com/810438/161439232-a28d99a4-b86e-42b0-be70-7b3df45c88b4.png">

**Comment by aigoncharov** [comment] 2022-04-04 13:57
We also see it in [Flipper](https://github.com/facebook/flipper). Rolling back to `ReactDOM.render` instead of `createRoot` seems to help.
We also managed to find a hacky patch. As @gaearon pointed out, the underlying issue seems to come from [here](https://github.com/react-component/trigger/blob/5f4bf49cd68a8b3cc80dde68d9650729ec242562/src/Popup/PopupInner.tsx#L126). `alignedClassName` is always `undefined`. 
If we replace 
```tsx
Promise.resolve().then(() => {
            forceAlign();
          });
```
with 
```tsx
new Promise(resolve => setTimeout(resolve)).then(() => {
            forceAlign();
          });
```
it seems to work again. 
My gut tells me that it might be because of the automatic batching of state updates in React 18.

**Comment by aigoncharov** [comment] 2022-04-13 18:40
I believe it should be resolved by https://github.com/react-component/trigger/commit/017131d9afdc0181a8f2441370ff938386aa1212

**Comment by brunolemos** [comment] 2022-04-16 06:59
Latest version is working fine, thanks!

**Closed** 2022-04-16 06:59 UTC

**Comment by Damon0820** [comment] 2025-04-11 12:44
In a React 18 environment, modal freezes are most likely caused by this issue. 
@zombieJ  react18环境下，弹窗类卡死，可能大部分都是这个原因。我也遇到这个问题了。rc-trigger从5.2.10升级到5.3.4解决。
